name: Deploy
on:
  push:
    branches: [main]

jobs:
  cleaning:
      name: Clean gh-pages
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2
          with:
            ref: gh-pages

        - name: Remove non-version directories
          run: find . -maxdepth 1 -type d ! -regex "\(\.\/v?[0-9]+.[0-9]+.[0-9]+\)\|\."

        - name: Remove files
          run: find . -maxdepth 1 -type f -delete
        
        - name: Upload to GitHub Pages
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: .

  docs:
    name: Generate Website
    needs: cleaning
    runs-on: ubuntu-latest
    env:
      SPHINX_GITHUB_CHANGELOG_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2

      - name: Install dependencies
        run: pip install -r docs/requirements.txt && git clone https://github.com/openai/gym.git && pip install ./gym
      
      - name: Build
        run: sphinx-build -b dirhtml -v docs/source build
  
      - name: Upload to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/
          keep_files: true
