name: Versioning
on:
  push:
    tags: 
      - '*'

jobs:
  docs:
    name: Generate Website for new version
    runs-on: ubuntu-latest
    env:
      SPHINX_GITHUB_CHANGELOG_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1

      - name: Install dependencies
        run: pip install -r docs/requirements.txt && git clone -b ${{steps.tag.outputs.tag}} --single-branch https://github.com/openai/gym.git  && pip install ./gym
      
      - name: Build
        run: sphinx-build -b dirhtml -v docs/source build

      - name: Remove CNAME
        run: rm ./build/CNAME 
      
      - name: Copy injection script
        run: cp ./github/workflows/inject_version_menu.py ./build/scripts/inject_version_menu.py 

      - name: Upload to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/
          destination_dir: ${{steps.tag.outputs.tag}}
      - name: Checkout Github pages
        run: git checkout gh-pages
      
      - name: Inject Menu
        run: python ./scripts/inject_version_menu.py .
