name: Deploy
on:
  push:
    tag: 
      - 'v*'

jobs:
  docs:
    name: Generate Version Website
    runs-on: ubuntu-latest
    env:
      SPHINX_GITHUB_CHANGELOG_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Install dependencies
        run: pip install -r docs/requirements.txt && git clone https://github.com/mgoulao/gym.git && pip install ./gym
      
      - name: Build
        run: sphinx-build -b dirhtml -v docs/source build

      - name: Upload to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/
          publish_branch: ${{ github.ref }}